Create Ad Selection API Auction Reporting for Alpha.md
WICG/privacy-preserving-ads pull request #66
Opened 2024-09-04 15:56 UTC by murphys0709

2024-09-04 16:59 UTC, Brandr0id reviewed
What about just 'Auction Reporting.md' for the filename?

Should we also update the contents or link from other locations to help guide readers to this flow?

2024-09-10 20:34 UTC, erik-anderson requested changes

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +Edge is only supporting ad auctions that are hosted by the seller’s front end (SFE), within a Trusted Execution Environment (TEE). When auctions are completed, two types of reports are generated via
Nit: "User Defined Functions" -> "user-defined functions" and "UDF" -> "UDFs".

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +Additionally, reporting is available for interactions within embedded frames. These reports are generated by the reportEvent() API.
Nit: add blank line after this one.

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +-   A [Request Blob](https://github.com/WICG/turtledove/blob/36bf1d00641d5f42850ad6f97a64324b53b47c70/FLEDGE_browser_bidding_and_auction_API.md#request-blob-format), contains the following informatio
Nit: prefer not Title Casing things that aren't a proper name. "Request Blob" -> "request blob"

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +-   A [Request Blob](https://github.com/WICG/turtledove/blob/36bf1d00641d5f42850ad6f97a64324b53b47c70/FLEDGE_browser_bidding_and_auction_API.md#request-blob-format), contains the following informatio
Nit: add the word "which" before "contains."

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +    -   Interest Groups: Encoded and compressed list of interest groups.
Same not-title-casing feedback; "Interest Groups" -> "Interest groups".

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +    -   Interest Groups: Encoded and compressed list of interest groups.
Also applies to line 26.

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +Each UDF can only send a single report URL.  If multiple attempts are made, an exception will be thrown.
Nit: blank line after this one.

2024-09-10 20:34 UTC, erik-anderson commented on Auction Reporting.md
> +An optional mode is available that converts all bid-related information to the seller's preferred currency (in component auctions, for that component's seller). This is configured via the sellerCurre
Double space between "sellerCurrency" and "option"; change to a single space.

2024-09-11 17:21 UTC, erik-anderson approved these changes

2024-09-11 17:26 UTC, merged