Create Ad Selection API Attribution Reporting for Alpha.md
WICG/privacy-preserving-ads pull request #67
Opened 2024-09-04 16:56 UTC by murphys0709

2024-09-10 20:38 UTC, erik-anderson requested changes

2024-09-10 20:38 UTC, erik-anderson commented on Attribution Reporting.md
> +There are two types of attribution triggers – HTML based and Javascript based.
Nit: blank line after this one.

2024-09-10 20:38 UTC, erik-anderson commented on Attribution Reporting.md
> +HTML-based attribution triggers can be used for detecting conversions on a page when an \<img> or \<script> element loads.  You can register an attribution trigger by adding the attributionsrc attrib
Nit: fix double space between "attributionsrc" and "value".

2024-09-10 20:38 UTC, erik-anderson commented on Attribution Reporting.md
> +  const req = newXMLHttpRequest();
Space after "new"; "new XMLHttpRequest".

2024-09-10 20:38 UTC, erik-anderson commented on Attribution Reporting.md
> +Report windows designate  how often reports will be sent.  The fields for customizing these values are:
Nit: Fix double space between "designate" and "how"

2024-09-10 20:38 UTC, erik-anderson commented on Attribution Reporting.md
> +To send a report, the browser will make a non-credentialed (i.e. without session cookies) secure HTTP POST request to:
Nit: saying "HTTPS post request" would be more clear than "secure HTTP POST request"

2024-09-10 20:58 UTC, dmdabbs commented on Attribution Reporting.md
> +## Navigation Sources (Click)
Are these examples illustrative, or is the "attributionsrc with URL" style the sole supported option?

2024-09-11 17:01 UTC, erik-anderson approved these changes

2024-09-11 17:26 UTC, merged